#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "Helvetica Neue:Bold:12.0"
spacebar -m config background_color   0x00202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff884545
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   零 一 二 三 四 五 六 七 八 九 十
spacebar -m config power_icon_strip   🔋 🔌
spacebar -m config space_icon         💻
spacebar -m config clock_icon         🕑
spacebar -m config dnd_icon           🌙
spacebar -m config clock_format       "%d/%m/%y %R"

echo "spacebar configuration loaded.."
