#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Fire Code:Light:10.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
#                                            0xAARRGGBB
yabai -m config status_bar_background_dim    off
yabai -m config status_bar_background_color  0xff000000
yabai -m config status_bar_foreground_color  0xffffffff
yabai -m config status_bar_space_icon_strip  ♔ ♕ ♗ ♘ ♖ ♙ ♙ ♙ ♙ ♙
#                                       battery power
# yabai -m config status_bar_power_icon_strip  ↓ ↑
# yabai -m config status_bar_clock_icon        ♙
yabai -m config status_bar_space_underline_color 0xffffffff
yabai -m config status_bar_power_underline_color 0xffffffff
yabai -m config status_bar_clock_underline_color 0xffffffff

yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0x00000000
yabai -m config insert_window_border_color   0x00000000
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               40
yabai -m config left_padding                 40
yabai -m config right_padding                40
yabai -m config window_gap                   10


yabai -m rule --add app=Emacs manage=on
yabai -m rule --add app=emacs manage=on
yabai -m rule --add app=Spotify manage=off

echo "yabai configuration loaded.."
