#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

SPACEBAR_HEIGHT=$(sketchybar --query bar | jq '[.height, .y_offset | tonumber] | add')
# yabai -m config external_bar all:0:$SPACEBAR_HEIGHT
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_border_blur off
yabai -m config window_opacity_duration 0.0
# Don't set this option. Then it tries to animate
# yabai -m config window_animation_duration 0.0
yabai -m config window_shadow off
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xffc678dd
yabai -m config normal_window_border_color 0xff21242b
yabai -m config insert_window_border_color 0xff000000
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

if [ "$(uname -m)" == "arm64" ]; then
	yabai -m config window_border_radius 0
else
	yabai -m config window_border_radius 10
fi

yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 2

yabai -m rule --add app=Notes manage=off
yabai -m rule --add app=XQuartz manage=on
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Disk Utility" manage=off
yabai -m rule --add app="Messenger" title="Media Viewer" manage=off
yabai -m rule --add app="Finder" title="Copy" manage=off
yabai -m rule --add app="Unreal Editor" title="Message Log" manage=off
yabai -m rule --add app="Finder" title=" Info$" manage=off
yabai -m rule --add app="Firefox" title"Extension: (Tree Style Tab) - Close tabs?" manage=off
yabai -m rule --add app="Home" manage=off
yabai -m rule --add app="1Password" manage=off

yabai -m rule --add app="Calendar" manage=off space=3
yabai -m rule --add app="Spotify" manage=off space=3

~/.config/scripts/setup-default-spaces.sh 5

echo "yabai configuration loaded.."

# setting up borders
~/Projects/JankyBorders/bin/borders active_color=0xffc678dd inactive_color=0xff21242b width=2 2>/dev/null 1>&2 &
